### ISSUE TITLE
compileProtos failing with latest version of generator

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-talent#431]
The compile protos step is failing with the latest version of the generator:

```
2022-07-04 18:26:44,500 synthtool [ERROR] > Failed executing /synthtool/node_modules/.bin/compileProtos src:
    at Namespace.resolveAll (/synthtool/node_modules/protobufjs/src/namespace.js:308:25)
    at Namespace.resolveAll (/synthtool/node_modules/protobufjs/src/namespace.js:308:25)
    at Namespace.resolveAll (/synthtool/node_modules/protobufjs/src/namespace.js:308:25)
    at Namespace.resolveAll (/synthtool/node_modules/protobufjs/src/namespace.js:308:25)
    at Type.resolveAll (/synthtool/node_modules/protobufjs/src/type.js:304:21)
    at Field.resolve (/synthtool/node_modules/protobufjs/src/field.js:317:21)
    at Type.get (/synthtool/node_modules/protobufjs/src/type.js:155:45)
    at Type.set (/synthtool/node_modules/protobufjs/src/type.js:177:38)
    at Field.resolve (/synthtool/node_modules/protobufjs/src/field.js:268:94)
    at Type.lookupTypeOrEnum (/synthtool/node_modules/protobufjs/src/namespace.js:411:15)
Error: no such Type or Enum 'Interview' in Type .google.cloud.talent.v4beta1.Application

              ^
        throw Error("no such Type or Enum '" + path + "' in " + this);
```

@alexander-fenster for triage.

Refs: https://github.com/googleapis/nodejs-talent/pull/430

**Comment by sofisl** [comment]
This seemed to have resolved itself by updating the post processor image 🤷‍♀️
