### ISSUE TITLE
Error being given during talent api call

### ISSUE THREAD

**Issue by andrew-starosciak** [googleapis/nodejs-talent#56]
I have been having an issue regarding the Google Talent API and am working to resolve this.

```
[ExceptionsHandler] Following fields are missing or invalid (Possible reasons: non-numeric for double field +60725ms
Error: Following fields are missing or invalid (Possible reasons: non-numeric for double field
    at Http2CallStream.call.on (/Users/central/code/star/ui-core/node_modules/@grpc/grpc-js/build/src/client.js:102:45)
    at Http2CallStream.emit (events.js:194:15)
    at Http2CallStream.endCall (/Users/central/code/star/ui-core/node_modules/@grpc/grpc-js/build/src/call-stream.js:74:18)
    at handlingTrailers (/Users/central/code/star/ui-core/node_modules/@grpc/grpc-js/build/src/call-stream.js:163:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
### Framework
"@nestjs/common": "5.5.0",
    "@nestjs/core": "5.5.0",
    "@nestjs/typeorm": "^6.0.0",
### Node
v10.15.3

### Code

```
import  * as talent from '@google-cloud/talent';
const client = new talent.v4beta1.JobServiceClient({
credentials: {
        client_email: xxxx,
        private_key: 
}
});
const request = {
      parent: 'job-board-test-240502',
}
await client.searchJobs(request)
      .then(responses => {
        const resources = responses[0];
             for (const resource of resources) {
              console.log(resource);
             }
           })
           .catch(err => {
             console.error(err);
           });
  }
```

**Comment by bcoe** [comment]
@andrew-starosciak could you try the latest `v4` version of the talent API, and let us know if you're still having this issue?

**Comment by meredithslota** [comment]
Closing out; if you are still seeing this issue, please open a new issue and let us know which version you're using! Thanks. :)
